/* Generated by Yosys 0.36+58 (git sha1 ea7818d31, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

(* top =  1  *)
(* src = "output/logic_gate/logic_gate.v:8.1-20.10" *)
module logic_gate(a, b, c, d, e, f);
  (* src = "output/logic_gate/logic_gate.v:10.9-10.10" *)
  input a;
  wire a;
  (* src = "output/logic_gate/logic_gate.v:10.12-10.13" *)
  input b;
  wire b;
  (* src = "output/logic_gate/logic_gate.v:11.10-11.11" *)
  output c;
  wire c;
  (* src = "output/logic_gate/logic_gate.v:11.13-11.14" *)
  output d;
  wire d;
  (* src = "output/logic_gate/logic_gate.v:11.16-11.17" *)
  output e;
  wire e;
  (* src = "output/logic_gate/logic_gate.v:9.16-9.17" *)
  output [1:0] f;
  wire [1:0] f;
  (* src = "output/logic_gate/logic_gate.v:12.10-12.12" *)
  wire n2;
  (* module_not_derived = 32'd1 *)
  (* src = "output/logic_gate/logic_gate.v:16.11-16.31" *)
  INVHDMX U5 (
    .A(n2),
    .Z(d)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "output/logic_gate/logic_gate.v:17.12-17.44" *)
  AND2HDMX U6 (
    .A(a),
    .B(b),
    .Z(c)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "output/logic_gate/logic_gate.v:18.12-18.45" *)
  NOR2HDUX U7 (
    .A(a),
    .B(b),
    .Z(n2)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "output/logic_gate/logic_gate.v:19.12-19.39" *)
  NOR2HDUX U8 (
    .A(c),
    .B(n2),
    .Z(e)
  );
  assign f = { a, b };
endmodule
